{ lib, pkgs, dmsPackage, ... }:
{
  xdg.configFile."environment.d/90-dms.conf".text = ''
    LANG=zh_CN.UTF-8
    TERMINAL=kitty
    QT_QPA_PLATFORM=wayland
    QT_QPA_PLATFORMTHEME=gtk3
    QT_QPA_PLATFORMTHEME_QT6=gtk3
    ELECTRON_OZONE_PLATFORM_HINT=auto
  '';

  # Runs as this user during every `nrs` switch (home-manager activates under
  # the target user), so failures abort the rebuild instead of hiding in a
  # login-time service. First switch migrates from home-manager symlinks,
  # then DMS owns niri config from then on.
  home.activation.dmsSetup = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
    export PATH=${lib.makeBinPath [ pkgs.coreutils pkgs.kitty ]}:/run/wrappers/bin:$PATH
    dms=${dmsPackage}/bin/dms
    config_dir="''${XDG_CONFIG_HOME:-$HOME/.config}"
    if [ -L "$config_dir/niri/config.kdl" ]; then
      run rm -f "$config_dir/niri/config.kdl"
    fi
    if [ ! -f "$config_dir/niri/config.kdl" ]; then
      run "$dms" setup headless --compositor niri --force </dev/null
    fi
    if [ ! -f "$config_dir/niri/dms/binds.kdl" ]; then
      run "$dms" setup binds </dev/null
    fi

    # Migrate only the old default terminal binding, preserving other bindings.
    # Also handles the Ghostty default generated by `dms setup headless`.
    binds="$config_dir/niri/dms/binds.kdl"
    terminal_bind='^[[:space:]]*Mod\+T[[:space:]].*spawn "(foot|ghostty)"'
    if [ -f "$binds" ] && ${pkgs.gnugrep}/bin/grep -Eq "$terminal_bind" "$binds"; then
      run cp --backup=numbered "$binds" "$binds.before-kitty"
      run ${pkgs.gnused}/bin/sed -Ei '/^[[:space:]]*Mod\+T[[:space:]]/s/spawn "(foot|ghostty)"/spawn "kitty"/' "$binds"
    fi
  '';
}
