{ config, lib, pkgs, osConfig, ... }:
let
  dmsPackage = osConfig.programs.dank-material-shell.package;
in
{
  programs.foot.settings.main.include = "${config.xdg.configHome}/foot/dank-colors.ini";

  # Runs as this user during a DMS `nrs` switch (home-manager activates under
  # the target user), so failures abort the rebuild instead of hiding in a
  # login-time service. First switch migrates from home-manager symlinks,
  # then DMS owns niri config from then on.
  home.activation.dmsSetup = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
    export PATH=${lib.makeBinPath [ pkgs.coreutils pkgs.foot ]}:/run/wrappers/bin:$PATH
    dms=${dmsPackage}/bin/dms
    config_dir="''${XDG_CONFIG_HOME:-$HOME/.config}"
    if [ -L "$config_dir/niri/config.kdl" ]; then
      run rm -f "$config_dir/niri/config.kdl"
    fi
    if [ ! -f "$config_dir/niri/config.kdl" ]; then
      run "$dms" setup headless --compositor niri --force </dev/null
    fi
    if [ ! -f "$config_dir/niri/dms/binds.kdl" ]; then
      run "$dms" setup binds </dev/null
    fi

    # Migrate only the old default terminal binding, preserving other bindings.
    # Also handles the Ghostty default generated by `dms setup headless`.
    binds="$config_dir/niri/dms/binds.kdl"
    terminal_bind='^[[:space:]]*Mod\+T[[:space:]].*spawn "(kitty|ghostty)"'
    if [ -f "$binds" ] && ${pkgs.gnugrep}/bin/grep -Eq "$terminal_bind" "$binds"; then
      run cp --backup=numbered "$binds" "$binds.before-foot"
      run ${pkgs.gnused}/bin/sed -Ei '/^[[:space:]]*Mod\+T[[:space:]]/s/spawn "(kitty|ghostty)"/spawn "foot"/' "$binds"
    fi
  '';
}
